question_data = [
        {"category": "Science: Computers",
         "type": "boolean", "difficulty": "medium",
         "question": "The HTML5 standard was published in 2014.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                           "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]

